### ISSUE TITLE
Sending game information to players

### ISSUE THREAD

**Issue by silentaim** [silentaim/stratego#11]
1 . Send game information to both players about each other's pieces. 
Player 1 should receive a list of all his pieces and a list of all Player 2s pieces in "Generic" form.
Player 2 should receive a list of all his pieces and a list of all Player 1s pieces in "Generic" form.

2. On game start, randomly generate whose turn it is.
Send to both players if they are in BoardState MY_TURN or THEIR_TURN
For now, don't worry about setup

3. Duplicate from Animation issue, reveal type of enemy for players during an attack with a special message.

**Comment by silentaim** [comment]
Added third requirement

**Comment by silentaim** [comment]
@abroberts14 - almost complete with this issue, should be ready for next week

**Comment by abroberts14** [comment]
completed
