### ISSUE TITLE
Menu Button (Help Wanted)

### ISSUE THREAD

**Issue by jayeni** [silentaim/stratego#26]
create a menu button that shows gave info(instructions),similar Display as clicking a "vs Player" and a window pops up

**Comment by silentaim** [comment]
To clarify - the user will create a menu button that says "Info", similar to the other buttons. When the button is pressed, a simple System printout saying "Clicked" will prove that the button is functional. 

Other buttons currently exist to gain inspiration and coding style from.

**Comment by linlinlin3** [comment]
Hi, I am working on this issue. I want to make sure that do I just need to printout "Clicked" on Console  instead of window pops up?

**Comment by silentaim** [comment]
@linlinlin3 - Thank you for your contribution, merging soon.
