### ISSUE TITLE
(HELP WANTED) Create Players Online Text

### ISSUE THREAD

**Issue by silentaim** [silentaim/stratego#29]
Create a "Players Online" text at the bottom of the main menu

**Comment by ihabdulr** [comment]
Hey any guidance on how I can complete this issue?

**Comment by ihabdulr** [comment]
Sorry for the immense delay on me following up on this issue.

**Comment by silentaim** [comment]
Sorry for the delay @ihabdulr - we had changed up our client logic to only connect when the server is active. Luckily this now makes your task a lot easier.

In the MainMenu class, under the "Searching for a player..." text, draw in "Connected players: " + count. You can get the count from Global.getServer() which returns the Server class. The Server class has a method called getConnectedPlayers(), which returns an int of the players that are online.

So it should look something like this, where you replace "Text here" with the appropriate text:

![image](https://user-images.githubusercontent.com/8918512/38914515-a6029d1c-42ad-11e8-9aaa-41a2073e864f.png)

**Comment by silentaim** [comment]
@ihabdulr - Forgot to mention you will need to pull the latest feature, sorry about that!

**Comment by ihabdulr** [comment]
No problem thanks for the information,will let you'll know when it's complete.

**Comment by ihabdulr** [comment]
@silentaim am I pulling the feature branch and working off that?

**Comment by silentaim** [comment]
Completed: https://github.com/silentaim/stratego/pull/45
