### ISSUE TITLE
[Bug] AI doesn't do any meaningful moves

### ISSUE THREAD

**Issue by i-r-a** [silentaim/stratego#32]
When doing a vs AI game, the AI just moved one piece back and forth as I captured pieces. When I captured that specific piece, it kept reappearing on the board until it just took away my piece, without it showing up under lost pieces
![have a bissue](https://user-images.githubusercontent.com/35972917/38064507-47bd9932-32cc-11e8-8767-0cb1f997859b.PNG)
![w](https://user-images.githubusercontent.com/35972917/38064513-4e87ac1c-32cc-11e8-9958-3b8aec18d321.PNG)

**Comment by silentaim** [comment]
Fixed on most recent feature release
