### ISSUE TITLE
Alpha testing: Feature Request

### ISSUE THREAD

**Issue by jaredgav** [silentaim/stratego#41]
FEATURE REQUEST
Allow the player to place some of their playing pieces down. After a selected few are placed the player can then hit Auto-fill and instead of clearing the board and placing all the pieces, it should save the location of the pieces already placed. This would be nice if there are pieces players know where to place and other they wish the game to fill in for them.

**Comment by silentaim** [comment]
Thanks @jaredgav - This was also a comment made in the Beta release presentation. I'll certainly be working on this.

**Comment by silentaim** [comment]
Completed:
commit 932bc6d66e6f1126283ee0e857ede9b05cbd1f13
