### ISSUE TITLE
A single client can open a multiplayer game by closing window and re-requesting an opponent

### ISSUE THREAD

**Issue by mattCarapella** [silentaim/stratego#47]
From the menu in the client window, I click on "Play Vs. Player". When the "Searching for a player" box is open, I close the window then click on "Play Vs. Player" again. The original request is never cancelled and upon doing this a multiplayer game is opened with only myself on two different ports. When I close the game window, it closes the second but I'm still connected on the first port.
<img width="765" alt="screen shot 2018-04-19 at 10 23 57 pm" src="https://user-images.githubusercontent.com/20136866/39027544-864dae8e-4420-11e8-9e90-e6dc41c35164.png">
<img width="786" alt="screen shot 2018-04-19 at 10 24 22 pm" src="https://user-images.githubusercontent.com/20136866/39027559-927873ce-4420-11e8-85d8-06b8448abafc.png">
^ Here you can see two connections open and a game started. Both are me.

<img width="788" alt="screen shot 2018-04-19 at 10 24 31 pm" src="https://user-images.githubusercontent.com/20136866/39027575-a06ab596-4420-11e8-9951-844f4b4f52bf.png">
^ After I close the window, the first connection remains until the game is quit

**Comment by silentaim** [comment]
Very good catch, assigning to @abroberts14

**Comment by abroberts14** [comment]
Yes, thank you for the bug report. Will work on it.

**Comment by abroberts14** [comment]
Completed, thank you.
