### ISSUE TITLE
Alpha Testing [Bug] The piece can jump to anywhere they want

### ISSUE THREAD

**Issue by kai123456** [silentaim/stratego#48]
As the Rule says that the pieces cannot jump over another piece. But, when I play the game, the piece can jump to anywhere I click to. As to guessing where the flag is.
![image](https://user-images.githubusercontent.com/22746768/39033772-aee20a86-4441-11e8-80be-fbda68cfc2c8.png)

**Comment by silentaim** [comment]
Bug resolved on yesterday's feature branch.
