### ISSUE TITLE
Looking for game (Server)

### ISSUE THREAD

**Issue by silentaim** [silentaim/stratego#9]
After @jayeni adds UI functionality for "Looking for Game", use this to add a player into a queue. When there is more than 1 player in the queue, match up the two players and create a game session with those two clients.

No game information is needed, just the two players in a game session. The client and server won't need to actually do anything from here besides a system printout saying they were matched into a game.

**Comment by silentaim** [comment]
The UI functionality has been committed to feature branch. Use the looking for game message to start the searching process. When two players are matched to a game session, send a message back to the client for each player. For now only needs to be a printout or something simple like switching the player into an AI game (for testing).

**Comment by abroberts14** [comment]
Searching process is complete
